version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    platform: "linux/amd64"

  
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maindb
      POSTGRES_USER: defuser
      POSTGRES_PASSWORD: DimasRealnoYmniy
    platform: "linux/amd64"

  # Application Service
  app:
    container_name: blog
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    platform: "linux/amd64"

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: mrfelsgc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
